---
title: "820 Team Project"
author: "team 6"
date: "11/19/2019"
output: pdf_document
---

**Team 7 Members:** Kunpeng Huang, Yoki Liu, Lyufan Pan, Yunlei Zhou, Jiayuan Zou, Sherry Zuo
```{r}
## load the packages
library(readr)
library(ggplot2)
library(dplyr)
library(purrr)
library(cluster)
library(factoextra)
library(tidyverse)
library(skimr)
library(corrplot)
```

```{r}
## load the dataset
data<-read_csv("CC GENERAL.csv")
```

```{r}
colnames(data)<-tolower(colnames(data))
colnames(data)
```

```{r}
##Data Cleaning
cc<-data%>%select(-cust_id)
colmean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
cc <- replace(cc, TRUE, lapply(cc, colmean))
glimpse(cc)
skim(cc)
##There are 17 numeric variables and 8950 observations. Replace NAs with colmeans. 
```
```{r fig.width=12, fig.height=12}
cc_c<-cor(cc)
corrplot(cc_c,
         type="upper",
         diag=F,
         method="color",
         order="hclust")
```

```{r}
##Fit the PCA model
cc_pca=prcomp(cc, center=TRUE, scale=TRUE)
##Choose Dimensions
get_eigenvalue(cc_pca)
##Based on the eigenvalue, we want to choose eigenvalue>1, so we could choose Dimension with 5; however, since we want cumulative variance too small, we choose eigenvalue>0.7, so we choose Dimension with 8 which also has 85% of cumulative variance. 
```

